language: node_js
node_js:
  - node
addons:
  ssh_known_hosts: s9.mydevil.net
install:
  - npm ci
script:
  - npm run lint
  - npm run build
before_deploy:
  - openssl aes-256-cbc -K $encrypted_255bbf61c8ee_key -iv $encrypted_255bbf61c8ee_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: scp -rp $TRAVIS_BUILD_DIR/public/* $deploy_user@$deploy_host:$deploy_path/new.build && ssh $deploy_user@$deploy_host 'cd $deploy_path && rm -rf old.build && mv public_html old.build && mv new.build public_html && mkdir new.build && cp env/.htaccess public_html'
  on:
    tags: true
